language: node_js
branches:
  only:
    - website
    - master
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install
script:
    - npm run docs:build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
after_success:
  - ./deploy.sh
# deploy:
#     repo: ClusterWS/clusterws.github.io
#     provider: pages
#     local_dir: docs/.vuepress/dist
#     skip-cleanup: true
#     github-token: $GITHUB_TOKEN
#     keep-history: true
#     target-branch: master
#     on:
#         branch: master