language: node_js
branches:
  only:
    - website
node_js:
    - "10"
before_script:
    - npm install
script:
    - npm run docs:build
cache:
    directories:
        - "node_modules"
deploy:
    repo: ClusterWS/clusterws.github.io
    provider: pages
    local_dir: docs/.vuepress/dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    on:
        branch: website